language: cpp

cache: ccache
sudo: true
matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: precise
      compiler: clang
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

install:
  - which apt-get && sudo apt-get install libboost-system-dev libboost-thread-dev || true

script:
  - cd build
  - cmake .
  - make
  - ./json_test

notifications:
  irc: "irc.freenode.org#sirikata"
