language: cpp

branches:
  only:
  - master

cache: ccache
sudo: true
matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: gcc
      env: JSON_SPIRIT_CXX11=true
    - os: linux
      dist: precise
      compiler: clang
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: xenial
      compiler: clang
      env: JSON_SPIRIT_CXX11=true
    - os: osx
      compiler: gcc
    - os: osx
      compiler: gcc
      env: JSON_SPIRIT_CXX11=true
    - os: osx
      compiler: clang
    - os: osx
      compiler: clang
      env: JSON_SPIRIT_CXX11=true

install:
  - which apt-get && sudo apt-get install libboost-system-dev libboost-thread-dev || true

script:
  - cd build
  - cmake . -DJSON_SPIRIT_CXX11=${JSON_SPIRIT_CXX11}
  - make
  - ./json_test

notifications:
  irc: "irc.freenode.org#sirikata"
